// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1646261232);
user_pref("app.update.lastUpdateTime.region-update-timer", 1646261472);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1646260992);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1646261112);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1646261022);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1646261352);
user_pref("browser.region.update.updated", 1646260969);
user_pref("browser.search.region", "MX");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "America/Mexico_City");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1646260975305");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1646261232);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220106182030");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"5f21c096-ceda-44bf-95fb-9cecf12daa4e\",\"google@search.mozilla.org\":\"c164fb4e-3bf1-4a77-b32d-42bf7b8342b1\",\"ddg@search.mozilla.org\":\"9d4d2852-9a62-4fbc-9394-5715d29eef3f\",\"wikipedia@search.mozilla.org\":\"77c9453a-4659-45f0-89f0-2e5e24939102\",\"bing@search.mozilla.org\":\"e1a5a00c-00cb-4a23-bde6-bd347034ddd5\",\"drae@search.mozilla.org\":\"80a89e6c-b71b-4b6b-8f20-6b5d09a00a1d\"}");
user_pref("idle.lastDailyNotification", 1646261353);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "e03c2037-e351-45c2-93e3-8456e2f42d9");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.5.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1646261353);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1626756455894\"");
user_pref("services.settings.last_update_seconds", 1646261112);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1646261112);
user_pref("services.settings.thunderbird.search-config.last_check", 1646261112);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1646261112);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1646261353);
user_pref("toolkit.telemetry.cachedClientID", "ea6f16b5-09e9-4322-b3e5-e29ecb7b4334");
user_pref("toolkit.telemetry.previousBuildID", "20220106182030");
